### PR TITLE
Switch to github actions

### PR DESCRIPTION
**Pull request by syohex**

### CODE REVIEW

**Comment by syohex** [comment]
Hmm, Installing dependencies is failed on some older perl such as 5.16.

**Comment by skaji** [comment]
```
--> Working on Pod::Simple
Fetching http://www.cpan.org/authors/id/K/KH/KHW/Pod-Simple-3.41.tar.gz
-> OK
Unpacking Pod-Simple-3.41.tar.gz
Entering Pod-Simple-3.41
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (6.63_02)
Configuring Pod-Simple-3.41
Running Makefile.PL
ExtUtils::MakeMaker version 6.64 required--this is only version 6.6302 at Makefile.PL line 12.
BEGIN failed--compilation aborted at Makefile.PL line 12.
```

**Comment by skaji** [comment]
I will create an issue for Pod::Simple.

**Comment by syohex** [comment]
Thanks

**Comment by syohex** [comment]
It looks there are no issues other than `Pod::Simple` on older Perls.

**Comment by syohex** [comment]
Newer version of Pod::Simple is released and all tests are passed on all perl version.

**Review by skaji — APPROVED** [review]
lgtm

**Comment by syohex** [comment]
Thanks for reviewing, I've merged.

**Pull request merged**
