### PR TITLE
use lib "t/lib" in tests

### LINKED ISSUE #220: . removed from @INC
Tests fail with perl 5.26 (when running outside a cpan installer):
```
$ ./Build test
...
t/03_step.t .................................. Can't locate t/Util.pm in @INC (you may need to install the t::Util module) (@INC contains: /home/cpansand/.cpan/build/2017051309/Minilla-v3.0.10-0/blib/arch /home/cpansand/.cpan/build/2017051309/Minilla-v3.0.10-0/blib/lib /opt/perl-5.26.0-RC1/lib/site_perl/5.26.0/x86_64-linux /opt/perl-5.26.0-RC1/lib/site_perl/5.26.0 /opt/perl-5.26.0-RC1/lib/5.26.0/x86_64-linux /opt/perl-5.26.0-RC1/lib/5.26.0) at t/03_step.t line 6.
BEGIN failed--compilation aborted at t/03_step.t line 6.
t/03_step.t .................................. Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/05_metadata.t .............................. Can't locate t/Util.pm in @INC (you may need to install the t::Util module) (@INC contains: /home/cpansand/.cpan/build/2017051309/Minilla-v3.0.10-0/blib/arch /home/cpansand/.cpan/build/2017051309/Minilla-v3.0.10-0/blib/lib /opt/perl-5.26.0-RC1/lib/site_perl/5.26.0/x86_64-linux /opt/perl-5.26.0-RC1/lib/site_perl/5.26.0 /opt/perl-5.26.0-RC1/lib/5.26.0/x86_64-linux /opt/perl-5.26.0-RC1/lib/5.26.0) at t/05_metadata.t line 5.
BEGIN failed--compilation aborted at t/05_metadata.t line 5.
t/05_metadata.t .............................. Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
...
```

### PR DESCRIPTION
**Pull request by skaji**
fix #220 

This PR replaces `use t::Util;` by `use lib "t/lib";\nuse Util;` to support perls which do not have `.` in `@INC`.

I confirmed that `PERL_USE_UNSAFE_INC=0 prove -lr t` passed.

### CODE REVIEW

**Comment by skaji** [comment]
It seems that the installation of dependencies failed with perl 5.8.
https://travis-ci.org/tokuhirom/Minilla/jobs/232016377

* Regexp::Common requires perl 5.10
* PAUSE::Permissions requires perl 5.10
* TOML::Parser requires perl 5.10

@tokuhirom Can we drop the support for perl 5.8?

**Comment by tokuhirom** [comment]
There is no reason to actively drop 5.8 support.
We can't support 5.8 if dependency modules depended on 5.10+.

**Comment by tokuhirom** [comment]
Minil is an authorization tool for Perl5 module developers. Perl5 module developers may not use 5.8 :P

**Comment by skaji** [comment]
I rebased agianst current master that drops support for perl 5.8 a979bbd

**Comment by skaji** [comment]
I will merge this PR tomorrow, and release a new version to CPAN.

**Pull request merged**
